openapi: 3.0.0
info:
  title: Wally API
  description: API documentation for the Wally application, providing endpoints for chat, product recommendations, and review management.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /health:
    get:
      summary: Health check
      description: Check the status of the application.
      responses:
        '200':
          description: Application is running
          
  /chat:
    post:
      summary: Process chat queries
      description: Send a text or voice query for processing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The user's query
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The response to the query

  /products:
    get:
      summary: Get product recommendations
      description: Retrieve a list of recommended products based on user preferences.
      responses:
        '200':
          description: A list of recommended products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The product ID
                    name:
                      type: string
                      description: The product name
                    price:
                      type: number
                      format: float
                      description: The product price

  /reviews:
    post:
      summary: Submit a review
      description: Submit a review for a product.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                  description: The ID of the product being reviewed
                reviewText:
                  type: string
                  description: The text of the review
      responses:
        '201':
          description: Review submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message
                    example: Review submitted successfully.